services:
  - type: web
    name: desk-timer-backend
    env: php
    rootDir: BACKEND
    buildCommand: "composer install && php artisan key:generate"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    plan: free
    region: oregon
    phpVersion: 8.2
