services:
    db:
        image: mysql:8.0
        container_name: desktimer-db
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: desktimer
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
        driver: local
